# Generated by Django 6.1.1 on 2026-09-17 13:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique company employee identifier (e.g., EMP001)', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Full legal name of the employee', max_length=150)),
                ('email', models.EmailField(db_index=True, help_text='Work or primary email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contact telephone number', max_length=20)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('IT', 'IT'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations')], help_text='Primary department', max_length=50)),
                ('designation', models.CharField(help_text='Job title / role designation', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly or annual base compensation (must be non-negative)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('joining_date', models.DateField(help_text='Date employee joined the organization')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', help_text='Current employment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
